<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Cetak QR - {{ $record->nopol ?? $qr->kode_qr }}</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <style>
        /* Page size for printing sticker: A6 (105mm x 148mm) */
        @page {
            size: A6 portrait;
            margin: 3mm;
        }

        html,body{height:100%;margin:0;padding:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,'Helvetica Neue',Arial,color-scheme:light;color:#111}
        .wrap{min-height:100vh;display:flex;align-items:center;justify-content:center;flex-direction:column;padding:12px;background:#f7fafc}
        .card{background:#fff;padding:14px;border-radius:8px;border:1px solid #e5e7eb;display:flex;gap:12px;align-items:center;max-width:900px;width:100%;box-sizing:border-box}
        .qr-box{flex:0 0 auto;display:flex;align-items:center;justify-content:center;padding:6px;background:#fff;border-radius:6px}
        .info{flex:1 1 auto;min-width:0}
        .code{margin-top:6px;font-family:monospace;word-break:break-all;text-align:left;font-size:12px;color:#111}
        table{width:100%;border-collapse:collapse;font-size:12px}
        td{padding:6px 4px;vertical-align:top}
        td.label{width:28%;color:#4b5563;font-weight:600}
        td.sep{width:3%}
        td.value{font-weight:700;color:#111}
        .controls{margin-top:10px;display:flex;gap:8px;justify-content:flex-end}
        button{padding:7px 10px;border-radius:6px;border:1px solid #cbd5e1;background:#fff;cursor:pointer;font-size:13px}
        button#print-btn{background:#2563eb;color:#fff;border-color:#2563eb}

        @media (max-width:640px){
            .card{flex-direction:column;align-items:center}
            .info{text-align:center}
            td.label{width:40%}
            .controls{justify-content:center}
        }

        /* Print-specific styling to match A6 sticker size, add visible border and reduce overall size */
        @media print {
            html, body {
                width: 105mm;
                height: 148mm;
                margin: 0;
            }
            .wrap {
                min-height: auto;
                height: 100%;
                padding: 0;
                background: #fff;
                display: flex;
                align-items: center;
                justify-content: center;
            }
            /* smaller card to fit sticker, with visible border */
            .card {
                width: 95mm;               /* slightly smaller than A6 width */
                max-width: 95mm;
                height: auto;
                padding: 4mm;             /* smaller padding on print */
                border: 1px solid #111;   /* visible border on printed sticker */
                border-radius: 4px;
                box-shadow: none;
                gap: 8px;
                align-items: center;
                box-sizing: border-box;
            }
            /* Make the QR large but fit the A6 sticker (reduced) */
            .qr-box { padding: 0; }
            /* Target SVG generated by QrCode package */
            .qr-box svg, .qr-box img {
                width: 45mm !important;   /* reduced QR size for sticker */
                height: auto !important;
                display: block;
            }
            .info { padding-left: 6mm; }
            .code { font-size: 11px; text-align: left; margin-top: 4px; }
            table { font-size: 10px; }
            td{padding:4px 2px}
            td.label{width:32%}
            .controls { display: none; } /* hide buttons on print */
        }
    </style>
</head>
<body>
    <div class="wrap">
        <div class="card">
            <div class="qr-box">
                {!! QrCode::size(300)->margin(1)->generate($qr->kode_qr) !!}
            </div>

            <div class="info">
                <div class="code">{{ $qr->kode_qr }}</div>

                <table class="w-full" aria-label="Informasi Kendaraan">
                    <tr>
                        <td class="label">Nama Barang</td>
                        <td class="sep">:</td>
                        <td class="value">{{ $record->nama_barang }}</td>
                    </tr>
                    <tr>
                        <td class="label">Jenis</td>

                        <td class="value">{{ $record->jenis_barang }}</td>
                    </tr>
                    <tr>          <td class="sep">:</td>
                        <td class="value">{{ $record->jenis_barang }}</td>
                    </tr>
                    <tr>
                        <td class="label">Merek</td>
                        <td class="sep">:</td>
                        <td class="value">{{ $record->merk }}</td>
                    </tr>
                    <tr>
                        <td class="label">Kondisi</td>
                        <td class="sep">:</td>
                        <td class="value" style="font-style:italic;text-transform:uppercase;font-weight:600">
                            {{ $record->keterangan }}
                        </td>
                    </tr>
                    <tr>
                        <td class="label">Pemilik</td>
                        <td class="sep">:</td>
                        <td class="value">{{ $record->pemilik }}</td>
                    </tr>
                </table>

                <div class="controls">
                    <button onclick="copyQRCode(event)">Salin</button>
                    <button id="print-btn" onclick="window.print()">Print</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        function copyQRCode(evt) {
            const text = "{{ $qr->kode_qr }}";
            if (!text) return;
            navigator.clipboard?.writeText(text).then(() => {
                const btn = evt?.currentTarget;
                if (btn) {
                    const original = btn.innerText;
                    btn.innerText = 'Tersalin';
                    setTimeout(() => btn.innerText = original, 1200);
                }
            });
        }

        // Auto print then try to close (keeps previous behavior)
        window.addEventListener('load', function () {
            setTimeout(function () {
                if (new URLSearchParams(window.location.search).has('autoprint')) {
                    window.print();
                    setTimeout(function(){ try { window.close(); } catch(e) {} }, 500);
                }
            }, 200);
        });
    </script>
</body>
</html>
